/**
 * PIO-driven slot-2 bus servicer -- implementation.
 *
 * See bus.pio for the state-machine assembly and protocol notes.
 * This file wires the program onto PIO0 SM0 and runs the CPU-side
 * lookup loop.
 *
 * Stats are exposed via bus_get_stats() (declared in bus_interface.h)
 * so the existing heartbeat in main.c keeps working without changes.
 * We override the polled implementation's storage by giving bus_pio.c
 * its own counter set and a bus_get_stats() override.
 */

#include "bus_pio.h"
#include "bus_interface.h"
#include "sync_state.h"
#include "midi.h"

#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "hardware/uart.h"
#include "hardware/structs/sio.h"
#include "hardware/structs/pads_bank0.h"

#include "bus.pio.h"   // generated by pico_generate_pio_header()

// NEW SRAM-cart wiring (post-bringup, May 2026):
//   GP0..GP7   -> slot-2 pins 22..29 (A16..A23 = data D0..D7)
//   GP8..GP15  -> slot-2 pins 6..13  (A0..A7 = low address bits)
//   GP22,26,27,28 -> slot-2 pins A8..A11 (address high bits, sampled by CPU)
//   GP16       -> /CS2
//   GP17       -> /RD
// (GP18 = /WR, GP19 = /REQ, GP20/21 = MIDI -- not used by the PIO)
#define DATA_BASE   0       // GP0..GP7 = A16..A23 (cart-driven data)
#define DATA_COUNT  8
#define ADDR_BASE   8       // GP8..GP15 = A0..A7 (DS-driven low address bits)
#define ADDR_BITS   8       // low 8 address bits
#define ADDR_HIGH_A8_PIN   22
#define ADDR_HIGH_A9_PIN   26
#define ADDR_HIGH_A10_PIN  27
#define ADDR_HIGH_A11_PIN  28
#define ADDR_HIGH_BITS     4 // A8..A11 (address high nibble, sampled by CPU)
#define CS2_PIN     16
#define RD_PIN      17
#define WR_PIN      18      // unused by PIO; init below sets it to input + pull-up
#define IRQ_PIN     19      // unused by PIO; init below leaves it driven low

static PIO  s_pio = pio0;
static uint s_sm  = 0;
static uint s_offset = 0;

// Cached pointer to the live sync_state byte mirror -- captured at
// bus_pio_init() time so the per-cycle CPU work in core 1 is a
// single byte load instead of a function call + load. core 0's
// MIDI parser updates the underlying struct asynchronously.
static const uint8_t *s_sync_bytes = NULL;

// Diagnostic counters. Same fields as bus_interface.c's so the
// heartbeat format string in main.c doesn't have to change.
static volatile uint32_t s_cs2_edges        = 0;
static volatile uint32_t s_reads_served     = 0;
static volatile uint32_t s_writes_seen      = 0;   // PIO path doesn't handle writes
static volatile uint32_t s_last_address     = 0;
static volatile uint32_t s_last_address_rd  = 0;
static volatile uint32_t s_address_or       = 0;
static volatile uint16_t s_ad_pins_or       = 0;
static volatile uint8_t  s_last_byte_served = 0;

void bus_get_stats(bus_stats_t *out) {
    if (!out) return;
    out->cs2_active_edges   = s_cs2_edges;
    out->reads_served       = s_reads_served;
    out->writes_seen        = s_writes_seen;
    out->last_address       = s_last_address;
    out->last_address_at_rd = s_last_address_rd;
    out->address_or         = s_address_or;
    out->ad_pins_or         = s_ad_pins_or;
    out->last_byte_served   = s_last_byte_served;
}

bool bus_pio_init(void) {
    // Load the program into PIO0's instruction memory.
    s_offset = pio_add_program(s_pio, &slot2_bus_program);

    // Configure all PIO-driven pins. pio_gpio_init sets the GPIO
    // function to PIO0 so the state machine can drive/sample them.
    // - GP0..GP7  (data, driven by us)
    // - GP8..GP15 (address bits, sampled from DS; low 8 bits)
    // - GP16, GP17 (/CS2, /RD, sampled from DS)
    for (uint i = 0; i < DATA_COUNT; i++) {
        pio_gpio_init(s_pio, DATA_BASE + i);
    }
    for (uint i = 0; i < ADDR_BITS; i++) {
        pio_gpio_init(s_pio, ADDR_BASE + i);
    }
    gpio_init(ADDR_HIGH_A8_PIN);  gpio_set_dir(ADDR_HIGH_A8_PIN,  GPIO_IN); gpio_pull_down(ADDR_HIGH_A8_PIN);
    gpio_init(ADDR_HIGH_A9_PIN);  gpio_set_dir(ADDR_HIGH_A9_PIN,  GPIO_IN); gpio_pull_down(ADDR_HIGH_A9_PIN);
    gpio_init(ADDR_HIGH_A10_PIN); gpio_set_dir(ADDR_HIGH_A10_PIN, GPIO_IN); gpio_pull_down(ADDR_HIGH_A10_PIN);
    gpio_init(ADDR_HIGH_A11_PIN); gpio_set_dir(ADDR_HIGH_A11_PIN, GPIO_IN); gpio_pull_down(ADDR_HIGH_A11_PIN);
    pio_gpio_init(s_pio, CS2_PIN);
    pio_gpio_init(s_pio, RD_PIN);

    // Direction defaults: data pins as inputs (the program flips to
    // output during the /RD low window, then back). Address pins
    // ALWAYS inputs (DS drives them). /CS2 and /RD always inputs.
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, DATA_BASE, DATA_COUNT, false);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, ADDR_BASE, ADDR_BITS,  false);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, CS2_PIN,   1, false);
    pio_sm_set_consecutive_pindirs(s_pio, s_sm, RD_PIN,    1, false);

    // Build the SM config from the program defaults, then patch in
    // our pin assignments.
    pio_sm_config c = slot2_bus_program_get_default_config(s_offset);

    // `in pins, 8` reads the low address byte from GP8..GP15, so the
    // input base is GP8 (= ADDR_BASE). The upper address bits A8..A11
    // are sampled separately by the CPU from dedicated GPIO pins.
    // `out pins, 16` writes 16 bits starting at GP0 (= DATA_BASE) --
    // only the low 8 of those are actually driven thanks to the 0x00FF
    // pindir mask, but the OUT instruction still ticks through all 16
    // to cleanly clear the OSR for the pindir write that follows.
    sm_config_set_in_pins (&c, ADDR_BASE);
    sm_config_set_out_pins(&c, DATA_BASE, 16);

    // Run at full system clock (125 MHz). Each PIO instruction is
    // 8 ns, so wait-edge-to-sample is ~8 ns -- well inside the
    // cart's address window.
    sm_config_set_clkdiv(&c, 1.0f);

    // ISR config: shift LEFT so each `in pins, 4` lands the 4
    // sampled bits in ISR's low 4 positions (the next `in` would
    // shift the previous bits up and add new ones at the bottom).
    // Push then puts a 32-bit word into RX FIFO whose low nibble
    // is the address; CPU does `addr & 0xF` to extract.
    // (Shift-right would land them at bits 28..31, requiring the
    // CPU to do `addr >> 28` -- functionally equivalent but more
    // confusing to read.)
    // Auto-push off; we use explicit `push` in the PIO program.
    sm_config_set_in_shift (&c, false /*shift left*/, false /*no auto-push*/, 32);
    // OSR shifts out from LSB. CPU packs a 32-bit word into TX FIFO:
    //   bits 0..15  -> data (out pins, 16)   -- low 8 = the response byte
    //   bits 16..31 -> pindir mask (out pindirs, 16) -- 0x00FF
    sm_config_set_out_shift(&c, true /*shift right*/, false /*manual pull*/, 32);

    pio_sm_init(s_pio, s_sm, s_offset, &c);

    // Disable internal pulls on data pins -- they're driven (either
    // by us or by the DS), and weak pulls would fight the active
    // driver during transitions.
    for (uint i = 0; i < DATA_COUNT; i++) gpio_disable_pulls(DATA_BASE + i);

    // Address pins (GP8..GP15) get internal pull-DOWNs. The DS drives
    // them whenever /CS2 is low, so the pull-down loses to active
    // drive (good). But during brief moments of noise / partial
    // contact on a bodge wire, the pull-down keeps the line at 0
    // rather than floating to a random value -- which would mean
    // PIO captures a bogus address and CPU serves the wrong byte.
    // Biases noise toward "this address bit is 0" instead of random.
    for (uint i = 0; i < ADDR_BITS; i++) gpio_pull_down(ADDR_BASE + i);
    gpio_pull_down(ADDR_HIGH_A8_PIN);
    gpio_pull_down(ADDR_HIGH_A9_PIN);
    gpio_pull_down(ADDR_HIGH_A10_PIN);
    gpio_pull_down(ADDR_HIGH_A11_PIN);

    // Drive strength + slew rate for the data pins.
    //
    // Pico GPIOs default to 4 mA / slow slew. For driving the DS
    // slot-2 bus (whose drivers may be stronger or have residual
    // capacitance from the connector + traces) we want max drive
    // current and fast slew rate so the line transitions are
    // decisive within the few-ns window the DS samples on.
    // Only the 8 data outputs (GP0..GP7) need this -- the address
    // inputs don't drive anything.
    for (uint i = 0; i < DATA_COUNT; i++) {
        gpio_set_drive_strength(DATA_BASE + i, GPIO_DRIVE_STRENGTH_12MA);
        gpio_set_slew_rate     (DATA_BASE + i, GPIO_SLEW_RATE_FAST);
    }

    // /WR isn't used by the PIO program (v1 ignores writes from the
    // DS) but keep it as an input with pull-up so it idles high.
    gpio_init(WR_PIN);
    gpio_set_dir(WR_PIN, GPIO_IN);
    gpio_pull_up(WR_PIN);

    // IRQ line: output, idle low. Unused by v1 but set up so it has
    // a deterministic state on the slot-2 bus.
    gpio_init(IRQ_PIN);
    gpio_set_dir(IRQ_PIN, GPIO_OUT);
    gpio_put(IRQ_PIN, 0);

    // Cache the sync_state byte pointer for the per-cycle lookup.
    s_sync_bytes = (const uint8_t *)sync_state_get();

    pio_sm_set_enabled(s_pio, s_sm, true);
    return true;
}

// Address-decoded serve: PIO pushes the low 8 address bits to the RX
// FIFO on /CS2 fall; the CPU appends the high 4 bits (A8..A11) sampled
// from dedicated GPIOs to form a 12-bit offset, looks up that byte from
// the live sync_state mirror, and pushes the response back. The window
// is 4 KB (12-bit A0..A11); the sync_state struct lives at the bottom:
//   0x00..0x03  magic "STDS"
//   0x04        version
//   0x05        flags
//   0x06..0x07  _pad
//   0x08..0x0B  tick_counter
//   0x0C..0x0F  bpm_q8
//   0x10..0x13  micros
//   0x14..0x15  song_pos_16ths
//   0x16        midi_write_head  (cart writes)
//   0x17        midi_read_head   (DS writes via trigger; advisory)
//   0x18..0x57  midi_ring[16] (4B ea)
//   0x58..0xFD  _reserved
// Offsets past the struct read back as zero (state_buf is zeroed).
// Offsets 0xE0..0xE3 are "MIDI TX trigger" addresses -- DS-side reads
// of these offsets cause the cart to emit a fixed MIDI byte out
// UART TX as a side effect. The read still returns sync_state's byte
// at that offset (= 0x00 from the _reserved area), so DS-side code
// can use the standard volatile-load pattern; it just discards the
// returned value. This avoids needing bus-write PIO support for v1
// MIDI OUT.
//   0xE0  -> 0xF8 (clock)
//   0xE1  -> 0xFA (start)
//   0xE2  -> 0xFC (stop)
//   0xE3  -> 0xFB (continue)
#define MIDI_TX_TRIG_BASE  0xE0u
#define MIDI_TX_TRIG_LAST  0xE3u

// Lookup table indexed by (addr - MIDI_TX_TRIG_BASE). 0 = no-op for
// safety (shouldn't be hit, but keeps the indexing clean).
static const uint8_t midi_tx_bytes[4] = {
    0xF8u,   // 0xE0 -> clock
    0xFAu,   // 0xE1 -> start
    0xFCu,   // 0xE2 -> stop
    0xFBu,   // 0xE3 -> continue
};

static inline void serve_one(uint32_t addr, uint8_t byte) {
    (void)addr;
    (void)byte;
    s_cs2_edges++;
    s_reads_served++;
}

static inline uint32_t read_addr_high_nibble(void) {
    uint32_t pins = sio_hw->gpio_in;
    return ((pins >> ADDR_HIGH_A8_PIN) & 1u)
         | (((pins >> ADDR_HIGH_A9_PIN) & 1u) << 1)
         | (((pins >> ADDR_HIGH_A10_PIN) & 1u) << 2)
         | (((pins >> ADDR_HIGH_A11_PIN) & 1u) << 3);
}

// Issue a MIDI byte out UART TX if the DS-read address fell in the
// trigger range. Non-blocking: if the TX FIFO happens to be full we
// silently drop the byte rather than starve the bus servicer (the
// TX FIFO is 32 bytes deep and we send at most ~50 bytes/sec at
// 120 BPM, so this should never actually drop in practice).
static inline void midi_tx_dispatch(uint32_t addr) {
    uint32_t a = addr & 0xFFu;
    if (a < MIDI_TX_TRIG_BASE || a > MIDI_TX_TRIG_LAST) return;
    if (!uart_is_writable(MIDI_UART)) return;
    uart_putc_raw(MIDI_UART, midi_tx_bytes[a - MIDI_TX_TRIG_BASE]);
}

void bus_pio_service_blocking(void) {
    // Block on the 8-bit low address byte from PIO. Read the high
    // address nibble from the extra GPIO pins and form a 12-bit
    // address for the new 4 KB window.
    uint32_t addr_lo = pio_sm_get_blocking(s_pio, s_sm) & 0x00FFu;
    uint32_t addr_hi = read_addr_high_nibble();
    uint32_t addr = (addr_hi << 8) | addr_lo;
    uint8_t  b    = s_sync_bytes[addr];

    // Response word: low 16 = data (low 8 = the byte), high 16 =
    // pindir mask 0x00FF (drive GP0..GP7 only).
    pio_sm_put_blocking(s_pio, s_sm,
                        ((uint32_t)0x00FFu << 16) | (uint32_t)b);

    serve_one(addr, b);
    midi_tx_dispatch(addr);
}

bool bus_pio_service_nonblocking(void) {
    if (pio_sm_is_rx_fifo_empty(s_pio, s_sm)) return false;
    if (pio_sm_is_tx_fifo_full (s_pio, s_sm)) return false;

    uint32_t addr_lo = pio_sm_get(s_pio, s_sm) & 0x00FFu;
    uint32_t addr_hi = read_addr_high_nibble();
    uint32_t addr = (addr_hi << 8) | addr_lo;
    uint8_t  b    = s_sync_bytes[addr];

    pio_sm_put(s_pio, s_sm,
               ((uint32_t)0x00FFu << 16) | (uint32_t)b);

    serve_one(addr, b);
    midi_tx_dispatch(addr);
    return true;
}
